version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demobase
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - '2001:2001'
    environment:
      PG_HOST: host.docker.internal #connect container to  host machine’s Postgres instance#Or# Connect to postgres container by service name{PG_HOST: postgres  }
      PG_USER: postgres
      PG_PASSWORD: admin
      PG_DATABASE: demobase
      PG_PORT: 5432
    depends_on:
      - postgres

  frontend:
    build: ./reactweb
    ports:
      - '3000:80'               # nginx serves on 80, exposed to host on 3000
    depends_on:
      - backend

volumes:
  pgdata:
